[package]
name = "pacman-bintrans"
version = "0.3.0"
description = "Binary transparency for pacman"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/pacman-bintrans"
categories = ["command-line-utilities"]
readme = "README.md"
edition = "2018"

[workspace]
members = ["pacman-bintrans-sign",
           "pacman-bintrans-monitor",
           "pacman-bintrans-common"]

[dependencies]
pacman-bintrans-common = { version = "0.3", path = "pacman-bintrans-common" }
env_logger = "0.9"
tokio = { version = "1", features = ["process", "macros", "rt-multi-thread", "time"] }
futures-util = "0.3.5"
toml = "0.5.6"
serde = "1.0.115"
tempfile = "3.2.0"
minisign = "0.7"
url = "2.2.2"
sha2 = "0.10"
hex = "0.4.3"
indicatif = "0.16.2"
rebuilderd-common = "0.19"
serde_json = "1.0.73"
tar = "0.4.38"
clap = { version = "4.0.26", features = ["derive"] }
