[package]
name = "pacman-bintrans-sign"
version = "0.3.0"
description = "Binary transparency for pacman - signing tools"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/pacman-bintrans"
categories = ["command-line-utilities"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
diesel = { version = "1.4", features = ["sqlite"] }
diesel_migrations = { version = "1.4", features = ["sqlite"] }
env_logger = "0.9.0"
minisign = "0.7"
pacman-bintrans-common = { version = "0.3", path = "../pacman-bintrans-common" }
tar = "0.4.37"
tempfile = "3.2.0"
tokio = { version = "1.10.0", features = ["process", "macros", "rt-multi-thread"] }
url = "2.2.2"
